### ISSUE TITLE
Next things to do

### ISSUE THREAD

**Issue by alonzi** [dkblack2013/CookingCharts#3]
I saw this at a bottom of a file so I put it here in an issue.

#Next things to do:
#1. Figure out how to make my data into a Shiny App
#2. Figure out how to pull data out of this online recipe
#3. If Step 2 fails, just pull it by hand and start building a catalog.

**Comment by dkblack2013** [comment]
#1 - I have built out the shell of a Shiny App, but the data won't display. See Issue #1 
#2 - I believe this will require some Natural Language Processing. 
#3 - This will be a stand-in for #2 until it's done.

**Comment by dkblack2013** [comment]
These issues are too broad, and I will update with more specific tasks to focus on next.
