### ISSUE TITLE
Code needs to identify individual sentences within a single string in order to separate them into individual instructions.

### ISSUE THREAD

**Issue by dkblack2013** [dkblack2013/CookingCharts#6]
Please help me write code that identifies each individual sentence within a string and separates that out into multiple strings.

**Comment by garretrc** [comment]
`s = "Hey David. This is Rob. I think this R function will be helpful for you. If you want to allow decimals like 1.0 without splitting, you can use period+space as your search string."`
`strsplit(s,"\\.")`
`strsplit(s,"\\. ")`
`strsplit(s,". ",fixed=TRUE) #match literal string, not regex (less flexible but easier)`
